# Copyright © 2020 Peter M. Stahl pemistahl@gmail.com
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either expressed or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

language: rust

rust: stable

sudo: required

cache: cargo

before_cache:
  - rm -rf "$TRAVIS_HOME/.cargo/registry/src"
  # Travis can't cache files that are not readable by "others"
  - chmod -R a+r $TRAVIS_HOME/.cargo

before_script: rustup target add $TARGET

matrix:
  include:
    - name: Linux 64-Bit
      os: linux
      env: TARGET=x86_64-unknown-linux-musl
      addons:
        apt:
          packages:
            - musl-tools
            - libssl-dev
      after_success: |
        cargo install cargo-tarpaulin -f
        cargo tarpaulin --verbose --ciserver travis-ci --out Xml
        bash <(curl -s https://codecov.io/bash)
        echo "Uploaded code coverage report"

    - name: MacOS 64-Bit
      os: osx
      env: TARGET=x86_64-apple-darwin MACOSX_DEPLOYMENT_TARGET=10.7

    - name: Windows 64-Bit
      os: windows
      env: TARGET=x86_64-pc-windows-msvc

script:
  - cargo build --target $TARGET --locked
  - cargo build --target $TARGET --locked --release
  - cargo test --target $TARGET